//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPER.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIPER.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average downtime time.
        /// </summary>
        public static string AverageDowntimeTime {
            get {
                return ResourceManager.GetString("AverageDowntimeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average refusal time.
        /// </summary>
        public static string AverageRefusalTime {
            get {
                return ResourceManager.GetString("AverageRefusalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average work time.
        /// </summary>
        public static string AverageWorkTime {
            get {
                return ResourceManager.GetString("AverageWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate equations.
        /// </summary>
        public static string CalculateEquations {
            get {
                return ResourceManager.GetString("CalculateEquations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of probability of system downtime:.
        /// </summary>
        public static string ChartDownTime {
            get {
                return ResourceManager.GetString("ChartDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of probability of system failure:.
        /// </summary>
        public static string ChartRefusal {
            get {
                return ResourceManager.GetString("ChartRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of probability of system work:.
        /// </summary>
        public static string ChartWork {
            get {
                return ResourceManager.GetString("ChartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Form.
        /// </summary>
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelect {
            get {
                return ResourceManager.GetString("DeleteSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downtime State.
        /// </summary>
        public static string DowntimeState {
            get {
                return ResourceManager.GetString("DowntimeState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element count.
        /// </summary>
        public static string ElementCount {
            get {
                return ResourceManager.GetString("ElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ElementPosition {
            get {
                return ResourceManager.GetString("ElementPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System of differential equations and Charts of reliability.
        /// </summary>
        public static string EquationTabName {
            get {
                return ResourceManager.GetString("EquationTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! End Node {0} must have conected!.
        /// </summary>
        public static string ErrorEndNode {
            get {
                return ResourceManager.GetString("ErrorEndNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Line  &apos;{0}&apos; hasn&apos;t got input element!.
        /// </summary>
        public static string ErrorInputLine {
            get {
                return ResourceManager.GetString("ErrorInputLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Module &apos;{0}&apos;  hasn&apos;t got input line!.
        /// </summary>
        public static string ErrorInputModule {
            get {
                return ResourceManager.GetString("ErrorInputModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Determine the working capacity condition..
        /// </summary>
        public static string ErrorNoCondition {
            get {
                return ResourceManager.GetString("ErrorNoCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Node {0} must have more than one connection line!.
        /// </summary>
        public static string ErrorNode {
            get {
                return ResourceManager.GetString("ErrorNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Line  &apos;{0}&apos; hasn&apos;t got output element!.
        /// </summary>
        public static string ErrorOutputLine {
            get {
                return ResourceManager.GetString("ErrorOutputLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Module &apos;{0}&apos;  hasn&apos;t got ouput line!.
        /// </summary>
        public static string ErrorOutputModule {
            get {
                return ResourceManager.GetString("ErrorOutputModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Start Node {0} must have conected!.
        /// </summary>
        public static string ErrorStartNode {
            get {
                return ResourceManager.GetString("ErrorStartNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Condition.
        /// </summary>
        public static string GetCondition {
            get {
                return ResourceManager.GetString("GetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get reliability  rating.
        /// </summary>
        public static string GetRating {
            get {
                return ResourceManager.GetString("GetRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph of states.
        /// </summary>
        public static string GraphTabName {
            get {
                return ResourceManager.GetString("GraphTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log table.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability determination system.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open scheme.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of system downtime.
        /// </summary>
        public static string ProbabilityDownTime {
            get {
                return ResourceManager.GetString("ProbabilityDownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of system failure.
        /// </summary>
        public static string ProbabilityRefusal {
            get {
                return ResourceManager.GetString("ProbabilityRefusal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability of system work.
        /// </summary>
        public static string ProbabilityWork {
            get {
                return ResourceManager.GetString("ProbabilityWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusal State.
        /// </summary>
        public static string RefusalState {
            get {
                return ResourceManager.GetString("RefusalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliability Window.
        /// </summary>
        public static string ReliabilityWindowTitle {
            get {
                return ResourceManager.GetString("ReliabilityWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runge Kutta Method.
        /// </summary>
        public static string RungeTabName {
            get {
                return ResourceManager.GetString("RungeTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save scheme as....
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Charts of reliability.
        /// </summary>
        public static string ShowCharts {
            get {
                return ResourceManager.GetString("ShowCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Graph.
        /// </summary>
        public static string ShowGraph {
            get {
                return ResourceManager.GetString("ShowGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of downtime states.
        /// </summary>
        public static string SumDownTiimeStates {
            get {
                return ResourceManager.GetString("SumDownTiimeStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of refusal states.
        /// </summary>
        public static string SumRefusalStates {
            get {
                return ResourceManager.GetString("SumRefusalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of working states.
        /// </summary>
        public static string SumWorkingStates {
            get {
                return ResourceManager.GetString("SumWorkingStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use modules repair.
        /// </summary>
        public static string UseRepair {
            get {
                return ResourceManager.GetString("UseRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working State.
        /// </summary>
        public static string WorkingState {
            get {
                return ResourceManager.GetString("WorkingState", resourceCulture);
            }
        }
    }
}
